//
// Created by sunvy on 20/04/2026.
//

#ifndef TERRARIA_BLOCKS_H
#define TERRARIA_BLOCKS_H

#include <array>
#include <cstdint>
#include <string>

struct Block
{
    enum
    {
        air = 0,
        dirt,
        grassBlock,
        stone,
        grass,
        sand,
        sandRuby,
        sandStone,
        woodPlank,
        stoneBricks,
        clay,
        woodLog,
        leaves,
        copper,
        iron,
        gold,
        copperBlock,
        ironBlock,
        goldBlock,
        bricks,
        snow,
        ice,
        rubyBlock,
        platform,
        workBench,
        glass,
        furnace,
        painting,
        sappling,
        snowBlueRuby,
        blueRubyBlock,
        door,
        jar,
        table,
        wordrobe,
        bookShelf,
        snowBricks,
        iceTable,
        iceWordrobe,
        iceBookShelf,
        icePlatform,
        sandTable,
        sandWordrobe,
        sandBookShelf,
        sandPlatform,
        woodenChest,
        iceChest,
        sandChest,
        boneChest,
        boneBricks,
        boneBench,
        boneWordrobe,
        boneBookShelf,
        bonePlatform,
        dirtWall,
        stoneWall,
        woodWall,
        sandStoneWall,
        brickWall,
        glassWall,
        copperBlockWall,
        silverBlockWall,
        goldBlockWall,
        snowWall,
        sandWall,
        stoneBricksWall,
        rubyBlockWall,
        heroglyphWall,
        blueRubyWall,
        plankedWall,
        snowBrickWall,
        boneBrickWall,

        BLOCKS_COUNT,
    };

    std::uint16_t type = 0;

    static constexpr  std::array<std::string, BLOCKS_COUNT> blockNames = {
        "air",
        "dirt",
        "grassBlock",
        "stone",
        "grass",
        "sand",
        "sandRuby",
        "sandStone",
        "woodPlank",
        "stoneBricks",
        "clay",
        "woodLog",
        "leaves",
        "copper",
        "iron",
        "gold",
        "copperBlock",
        "ironBlock",
        "goldBlock",
        "bricks",
        "snow",
        "ice",
        "rubyBlock",
        "platform",
        "workBench",
        "glass",
        "furnace",
        "painting",
        "sappling",
        "snowBlueRuby",
        "blueRubyBlock",
        "door",
        "jar",
        "table",
        "wordrobe",
        "bookShelf",
        "snowBricks",
        "iceTable",
        "iceWordrobe",
        "iceBookShelf",
        "icePlatform",
        "sandTable",
        "sandWordrobe",
        "sandBookShelf",
        "sandPlatform",
        "woodenChest",
        "iceChest",
        "sandChest",
        "boneChest",
        "boneBricks",
        "boneBench",
        "boneWordrobe",
        "boneBookShelf",
        "bonePlatform",
        "sunsetShimmer",
        "stoneWall",
        "woodWall",
        "sandStoneWall",
        "brickWall",
        "glassWall",
        "copperBlockWall",
        "silverBlockWall",
        "goldBlockWall",
        "snowWall",
        "sandWall",
        "stoneBricksWall",
        "rubyBlockWall",
        "heroglyphWall",
        "blueRubyWall",
        "plankedWall",
        "snowBrickWall",
        "boneBrickWall"
    };
};

#endif //TERRARIA_BLOCKS_H